# Generated by Django 5.1 on 2024-08-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='balance',
            new_name='bal',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='balance',
            new_name='bal',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='balance',
            new_name='bal',
        ),
    ]
