# Generated by Django 5.1 on 2024-08-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
