# Generated by Django 5.1 on 2024-08-23 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_item_bal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilledItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sigst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit', models.CharField(blank=True, max_length=5, null=True)),
                ('item_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billed_item', to='bill.item')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('eway', models.CharField(max_length=25)),
                ('transport', models.CharField(max_length=20)),
                ('vehicle_no', models.CharField(max_length=15)),
                ('no_of_items', models.PositiveIntegerField(default=0)),
                ('other_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tgst_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total_words', models.CharField(max_length=150, null=True)),
                ('invoice_items', models.ManyToManyField(to='bill.billeditem')),
                ('invoice_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.customer')),
            ],
        ),
    ]
