# Generated by Django 5.1 on 2024-08-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0012_billeditem_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
