# Generated by Django 5.1 on 2024-08-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0015_alter_bank_user_alter_billeditem_item_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acno',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_ifsc',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
