# Generated by Django 5.1 on 2024-08-29 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0018_remove_payment_party_payment_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_item',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employee_item',
            name='item',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='person_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='supplier',
        ),
        migrations.AddField(
            model_name='payment',
            name='party',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bill.customer'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Employee_Item',
        ),
    ]
