# Generated by Django 5.1 on 2024-08-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0019_remove_employee_item_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billeditem',
            name='dis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
