# Generated by Django 5.1 on 2024-08-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0022_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='user',
        ),
        migrations.AddField(
            model_name='bank',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='acno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='branch',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='ifsc',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
